defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"
plugins: [jekyll-paginate]

title: 日本物理学会 計算物理領域
subtitle: 

# left_side:
#   background_image: "./assets/images/left-background.jpg"
#   background_color: "#F00"
#   close_button_color: "#F00"
#   text_color: "#F00"

footer:
  copyright_text: "&copy; 日本物理学会 計算物理領域"

# Side Menu Links
menu:
  - text: ニュース
    link: /
    icon: ""

  - text: 計算物理メーリングリスト
    link: /mailinglist
    icon: ""

  - text: 計算物理領域代表・運営委員
    link: /members
    icon: ""

  - text: 計算物理領域準備会 (-2024)
    link: https://sites.google.com/view/compphys-jp
    icon: ""

  - text: 日本物理学会
    link: http://www.jps.or.jp/
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/christianezeani
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/christianezeani
    icon: fab fa-github-square

  - name: facebook
    link: https://www.facebook.com/christian.ezeani.cyb
    icon: fab fa-facebook-square

  - name: twitter
    link: https://www.twitter.com/christianezeani
    icon: fab fa-twitter


    
